config/routes.rb
Rails.application.routes.draw do

  namespace :cpanel do
    resources :jobs, only:[:index, :destroy]
  end

  get '/about' => 'pages#about', :as => 'about'

  devise_for :users

  resources :jobs do
    member do
      put :open
      put :close
    end
    collection do
      post :preview
      put :preview
    end
  end

  root to: 'jobs#index'
  match '*unmatched_route', to: redirect{'/'}, via: :all

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessor :deadline_forever

  SearchableColumns = [:title, :job_type, :occupation, :company_name, :url, :location, :description, :apply_information]

  validates_presence_of :title
  validates_presence_of :job_type
  validates_presence_of :company_name
  validates_presence_of :occupation
  validates_presence_of :location
  validates_presence_of :description
  validates_presence_of :apply_information
  validates_presence_of :owner

  validates_format_of :description, with: /(ruby|rails)/i, message: "Doesn't seem to be a Ruby or Rails related job"
  JOB_TYPE = %w(Full-time Part-time Contract Internship Other)
  OCCUPATION = ['Web back-end', 'Web front-end', 'Web-design',
                'QA/Testing', 'Other']

  validates_inclusion_of :job_type, in: JOB_TYPE
  validates_inclusion_of :occupation, in: OCCUPATION

  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'

  before_validation :set_aasm_state, on: :create
  before_validation :set_deadline

  scope :published, -> { where(aasm_state: 'published') }
  scope :online, -> { published.where('deadline is NULL or deadline > ?', Date.today) }
  scope :recent, -> {order('id DESC')}

  def self.search(keyword)
    kw = "%#{keyword.downcase}%".to_sym
    where(
      SearchableColumns.map{|col_name| "LOWER(#{col_name}) LIKE ? "}.join(" OR "),
      *SearchableColumns.map{kw}
    )
  end

  def open
    self.aasm_state = 'published'
  end

  def close
    self.aasm_state = 'closed'
  end

  def closed?
    aasm_state == 'closed'
  end

  def to_param
    "#{id}-#{title} #{company_name}".to_slug.normalize.to_s
  end

  def social_link_url
    CGI.escape "http://jobs.ruby.tw/jobs/#{to_param}"
  end

  def social_link_title
    CGI.escape title
  end

  def social_link_content
    "#{social_link_title} #{social_link_url}"
  end

  def deadline_forever
    !deadline
  end

  def owned_by?(user)
    !!(user && owner == user)
  end

  private

  def set_deadline
    self.deadline = nil if deadline_forever == '1'
  end

  def set_aasm_state
    self.aasm_state = 'published'
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  def admin?
    name == "admin".freeze
  end
end

app/models/setting.rb
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation

  has_many :jobs

  belongs_to :role

  delegate :admin?, to: :role, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :set_locale

  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found
  rescue_from ActionController::RoutingError, with: :not_found

  def not_found
    render text: 'Not found'
  end

  protected

  def set_locale
    if params[:locale] && %w(en zh_tw).include?(params[:locale])
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale
  end

  def render_not_found
    render template: 'pages/404', status: 404
  end
end

app/controllers/cpanel/jobs_controller.rb
class Cpanel::JobsController < ApplicationController
  layout 'cpanel' 
  before_action :admin_only

  def index
    if params[:user_id]
      @jobs = User.find(params[:user_id]).jobs.recent
    elsif params[:keyword]
      @jobs = Job.online.search(params[:keyword])
    else
      @jobs = Job.online.recent
    end
  end

  def destroy
    @jobs = Job.find(params[:id])
    @jobs.destroy
    redirect_to cpanel_jobs_path, :alert => '職缺已刪除'
  end

  private
  def admin_only
    redirect_to root_path unless current_user && current_user.role.name == 'admin'
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_my_job, only: [:edit, :update, :destroy, :open, :close]

  def index
    if params[:user_id]
      @jobs = User.find(params[:user_id]).jobs.recent
    elsif params[:keyword]
      @jobs = Job.online.search(params[:keyword])
    else
      @jobs = Job.online.recent
    end
  end

  def show
    @job = Job.find(params[:id])

    set_page_title "#{@job.title} | #{@job.company_name} is hiring!"
    set_page_description @job.description
  end

  def new
    @job = current_user.jobs.build
    @job.deadline = Time.zone.now + 90.days
  end

  def create
    @job = current_user.jobs.build(job_params)

    if @job.save
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  def edit
  end

  def preview
    @job = current_user.jobs.build(params[:job])
    @job.created_at = Time.now
    @job.valid?

    render layout: false
  end

  def update
    if @job.update_attributes(job_params)
      redirect_to job_path(@job)
    else
      render :edit
    end
  end

  def destroy
    @job.destroy

    redirect_to jobs_path
  end

  def open
    @job.open
    @job.save!

    redirect_to job_path(@job)
  end

  def close
    @job.close
    @job.save!

    redirect_to job_path(@job)
  end

  protected

  def job_params
    params.require(:job).permit(:title, :job_type, :occupation, :company_name, :location, :url, :description, :apply_information, :deadline, :user_id, :deadline_forever)
  end

  def find_my_job
    @job = current_user.jobs.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=174126862200";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-145330-14']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_search_form.html.erb
<%= form_tag jobs_path, :id => "search-form", :class => "search", :method => :get do %>
  <%= text_field_tag :keyword, "", :title => "Search", :class => "text" %>
  <%= submit_tag t(:search), :disable_with => t(:submiting), :class => "search-submit" %>
<% end %>

app/views/common/_usernav.html.erb
<% if user_signed_in? %>
  Hi, <%= current_user.email %> 
  <%= link_to t(:list_my_posting), jobs_path(current_user, :user_id => current_user) %> | 
  <%= link_to t(:settings), edit_user_registration_path %> |
  <% if current_user.admin? %>
  	<%= link_to "管理後台", cpanel_jobs_path %> |
  <% end %>
  <%= link_to t(:logout), destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to t(:signup), new_registration_path(:user) %> | 
  <%= link_to t(:login), new_session_path(:user) %>
<% end %>

app/views/cpanel/common/_menu.html.erb
<div class="menu-container">
  <ul class="menu-nav">
    <li class="menu-active">
    	<%= link_to cpanel_jobs_path, style: "text-decoration: none;" do %>
        <span class="menu_text">
        	<span class="glyphicon glyphicon-book" aria-hidden="true"></span> 職缺管理
        </span>
        <% end %>
    </li>
    <li>
      <a href="#">
        <span class="menu_text">
        	<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
        	待新增功能
        </span>
      </a>
      </li>
    <li>
      <a href="#">
        <span class="menu_text">
        	<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
        	待新增功能
        </span>
      </a>
      </li>
    <li>
      <a href="#">
        <span class="menu_text">
        	<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
        	待新增功能
        </span> 
      </a>
    </li>
    <li>
      <a href="#">
        <span class="menu_text">
        	<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
        	待新增功能
        </span>
      </a>
    </li>
  </ul>
</div>

app/views/cpanel/common/_navbar.html.erb
<header class="cpanel_menu">
	<div class="row">
		<div class="col-md-9">
			<div class="container">
					<div id="cpanel_logo">
						<%= link_to root_path do %>
							<%= image_tag("ruby_1.png", size: "50x50", style: "margin-right: 10px;") %>
		  					<h1>Ruby Jobs</h1>
		  				<% end %>
					</div>
  			</div>
		</div>

		<div class="col-md-3">
			<div class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
				<div class="cpanel_user">
					<li class="dropdown profile-dropdown admin_nolist">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<%#= image %>
							<span id="admin_user_menu">
							<%= current_user.email %>
							</span>
							<b class="caret"></b>
						</a>

						<ul class="dropdown-menu dropdown-menu-right">
							<% if current_user.admin? %>
								<li>
								  	<%= link_to cpanel_jobs_path do %>
									<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>　管理後台
									<% end %>
								</li>
							<% end %>
							<li>
								<%= link_to jobs_path(current_user, :user_id => current_user)  do %>
								<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>　查詢張貼職缺
								<% end %>
							</li>
							<li>
								<%= link_to edit_user_registration_path  do %>
								<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>　編輯會員資料
								<% end %>
							</li>
							<li>
								<%= link_to destroy_user_session_path, :method => :delete  do %>
								<span class="glyphicon glyphicon-off" aria-hidden="true"></span>　登出會員
								<% end %>
							</li>
						</ul>
					</li>
				</div>
			</div>
			<% else %>
				 <%= link_to t(:註冊), new_registration_path(:user) %> | 
  				<%= link_to t(:登入), new_session_path(:user) %>
			<% end %>
		</div>
	</div>
</header>

app/views/cpanel/jobs/index.html.erb
<p class="post-job clearfix"><%= link_to t("post_a_new_job"), new_job_path, :title => t("post_a_new_job") %></p>

<table cellspacing="0" class="joblist">
    <thead>
	<tr>
		<th><%= t("job.posted") %></th>
		<th><%= t("job.title") %></th>
		<th><%= t("job.company_name") %></th>
		<th><%= t("job.location") %></th>
		<th>管　理</th>
	</tr>
	</thead>
	<tbody>	
	<% @jobs.each do |job| %>
		<tr>
			<td><%= job.created_at.to_date %></td>
			<td><%= link_to job.title, job_path(job) %></td>
			<td><%= job.company_name %></td>
			<td><%= job.location %></td>
			<td>
				<%= link_to "刪除" , cpanel_job_path(job.id), method: :DELETE, class: 'btn_delete', data: { confirm: "確定刪除管理員權限?" } %>
			</td>
		</tr>
	<% end %>
    </tbody>
</table>
<span class="paperclip"></span>

app/views/jobs/_form.html.erb
<div class="form">
  <%= form_for @job do |f| %>

	<% if @job.errors.any? %>
	<div id="error_explanation">
  		<h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
  		<ul>
  			<% @job.errors.full_messages.each do |msg| %>
    		<li><%= msg %></li>
  			<% end %>
  		</ul>
	</div>
	<% end %>

	<div class="field">
	<%= f.label :title, t("job.title") %>
	<%= f.text_field :title, :class => "text" %>
	</div>
	
	<div class="field">
	<%= f.label :company_name, t("job.company_name") %>
	<%= f.text_field :company_name, :class => "text" %>
	</div>
	
	<div class="field">
	<%= f.label :url, "URL" %>
	<%= f.text_field :url, :class => "text" %>
	</div>
	
	<div class="field reset">
	<%= f.label :job_type, t("job.type") %>
		<% Job::JOB_TYPE.each do |t| %>
                        <%= f.radio_button :job_type, t %> <%= f.label :job_type, t, :value => t, :class => "inline" %>
		<% end %>
	</div>
	
	<div class="field reset">
	<%= f.label :occupation, t("job.occupation") %>
		<% Job::OCCUPATION.each do |o| %>
                        <%= f.radio_button :occupation, o %> <%= f.label :occupation, o, :value => o, :class => "inline" %>
		<% end %>
	</div>
		
	<div class="field">
	<%= f.label :location, t("job.location") %>
	<%= f.text_field :location, :class => "text" %>
	</div>
	
	<div class="field">
	<%= f.label :description, t("job.description") %>
	<%= f.text_area :description, :class => "text" %>
	</div>
	
	<div class="field">
	<%= f.label :apply_information, t("job.apply_information") %>
	<%= f.text_area :apply_information, :class => "text" %>
	</div>
	
	<div class="field reset">
		<%= f.label :deadline, t("job.deadline") %>
		<span id="deadline_fields"><%= f.date_select :deadline %></span>
		<%= f.check_box :deadline_forever %><label for="job_deadline_forever" class="inner"><%= t("job.deadline_forever") %></label>
	</div>
	
	<div class="field actions">
          <%= link_to(t(:preview), "#preview", :class => "preview") %>
	<%= f.submit t(:submit), :class => "submit button",:disable_with => t(:submiting) %>
	</div>
        <div style='display:none'>
        <div id="preview"></div>
        </div>
<% end %>
</div>

<%= content_for :scripts do %>

<script type="text/javascript" charset="utf-8">
  if ( $("#job_deadline_forever").attr("checked") ) {
      $("#deadline_fields").hide();
  }
  $("#job_deadline_forever").click(function() {
      $("#deadline_fields").toggle();
  });
    $("a.preview").colorbox( {
        width: "960px",
        height: "80%",
        inline: true,
        onLoad: function() {
          $.post("/jobs/preview", $("form").serialize(), function(s){ $("#preview").html(s)});
        }
    } );
</script>

<% end %>

app/views/jobs/_form.mobile.erb
  <%= form_for @job do |f| %>

	<% if @job.errors.any? %>
	<div class="error_explanation">
  		<h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
  		<ul>
  			<% @job.errors.full_messages.each do |msg| %>
    		<li><%= msg %></li>
  			<% end %>
  		</ul>
	</div>
	<% end %>

        <p>
          <%= f.label :title, t("job.title") %><br/>
	  <%= f.text_field :title, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :company_name, t("job.company_name") %><br/>
	  <%= f.text_field :company_name, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :url, "URL" %><br/>
	  <%= f.text_field :url, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :job_type, t("job.type") %><br/>
		<% Job::JOB_TYPE.each do |t| %>
                        <%= f.radio_button :job_type, t %> <%= f.label :job_type, t, :value => t, :class => "inline" %>
		<% end %>
        </p>
	
        <p>
          <%= f.label :occupation, t("job.occupation") %><br/>
		<% Job::OCCUPATION.each do |o| %>
                        <%= f.radio_button :occupation, o %> <%= f.label :occupation, o, :value => o, :class => "inline" %>
		<% end %>
        </p>
		
        <p>
          <%= f.label :location, t("job.location") %><br/>
	  <%= f.text_field :location, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :description, t("job.description") %><br/>
	  <%= f.text_area :description, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :apply_information, t("job.apply_information") %><br/>
	  <%= f.text_area :apply_information, :class => "text" %>
        </p>
	
        <p>
          <%= f.label :deadline, t("job.deadline") %><br/>
          <span class="deadline_fields"><%= f.date_select :deadline %></span>
          <%= f.check_box :deadline_forever %><label for="job_deadline_forever" class="inner"><%= t("job.deadline_forever") %></label>
        </p>
	
        <p>
          <%= link_to(t(:preview), "#", :class => "jobpreview") %>
	  <%= f.submit t(:submit), :class => "submit button",:disable_with => t(:submiting) %>
        </p>
<% end %>

app/views/jobs/_job.html.erb
          <ul class="job-info form menu">
                <li class="double clearfix">
                    <div class="field">
                        <label><%= t("job.type") %></label> <%= job.job_type %>
                    </div>
                    <div class="field">
                        <label><%= t("job.occupation") %></label> <%= job.occupation %>
                    </div>
                </li>
                <li class="double clearfix">
                    <div class="field">
                        <label><%= t("job.company_name") %></label> <%= job.company_name %>
                    </div>
                    <div class="field">
                        <label><%= t("job.location") %></label> <%= job.location %>
                    </div>
                </li>

				<% unless job.url.blank? %>
                <li>
                    <div class="field">
                        <label>URL</label> <%= raw auto_link job.url, :target => "_blank" %>
                    </div>
                </li>
				<% end %>
								
                <li class="last">
                    <div class="field">
                        <label><%= t("job.description") %></label>
                        <div class="description"><%= simple_format job.description %></div>
                    </div>
                </li>
            </ul>
            <div class="apply-information">
                <h2><%= t("job.apply_information") %></h2>
                <div class="description"><%= simple_format job.apply_information %></div>
            </div>

app/views/jobs/_job.mobile.erb
<dl title="job detail">
  <dt><%= t("job.posted") %></dt>
  <dd><%= job.created_at.to_date %></dd>

  <% if job.deadline %>
  <dt><%= t("job.deadline") %></dt>
  <dd><%= job.deadline %></dd>
  <% end %>

  <dt><%= t("job.type") %></dt>
  <dd><%= job.job_type %></dd>

  <dt><%= t("job.occupation") %></dt>
  <dd><%= job.occupation%></dd>

  <dt><%= t("job.company_name") %></dt>
  <dd><%= job.company_name%></dd>

  <dt><%= t("job.location") %></dt>
  <dd><%= job.location%></dd>

  <% unless job.url.blank? %>
  <dt>URL</dt>
  <dd><%= raw auto_link job.url, :target => "_blank" %></dd>
  <% end %>

  <dt><%= t("job.description") %></dt>
  <dd><%= simple_format job.description %></dd>

  <dt><%= t("job.apply_information") %></dt>
  <dd><%= simple_format job.apply_information %></dd>
</dl>

app/views/jobs/edit.html.erb
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<p class="post-job clearfix"><%= link_to t("post_a_new_job"), new_job_path, :title => t("post_a_new_job") %></p>

<table cellspacing="0" class="joblist">
    <thead>
	<tr>
		<th><%= t("job.posted") %></th>
		<th><%= t("job.title") %></th>
		<th><%= t("job.company_name") %></th>
		<th><%= t("job.location") %></th>
	</tr>
	</thead>
	<tbody>	
	<% @jobs.each do |job| %>
		<tr>
			<td><%= job.created_at.to_date %></td>
			<td><%= link_to job.title, job_path(job) %></td>
			<td><%= job.company_name %></td>
			<td><%= job.location %></td>
		</tr>
	<% end %>
    </tbody>
</table>
<span class="paperclip"></span>

app/views/jobs/index.mobile.erb
<div data-role="page">
  <header data-role="header" data-noBackBtn=true>
    <h1>Ruby Jobs in Taiwan</h1>
    <% if user_signed_in? %>
    <%= link_to 'Add', new_job_path, "data-icon" => "plus", "class" => "ui-btn-right" %>
    <% end %>
  </header>

  <div data-role="content">
    <ul data-role="listview">
      <% @jobs.each do |job| %>
      <li>
        <h3><%= link_to job.title, job_path(job) %></h3>
        <p><strong><%= job.company_name %></strong></p>
        <p><%= job.location %></p>
        <p class="ui-li-aside"><strong><%= job.created_at.to_date %></strong></p>
      </li>
      <% end %>
    </ul>
    <%= render "shared/foot" %>
  </div><!-- content -->


  <footer data-role="footer">
    <h4>Ruby.tw</h4>
  </footer>
</div>

app/views/jobs/new.html.erb
<h2 class="pagetitle"><%= t("post_a_new_job") %></h2>
<%= render :partial => 'form', :object => @job %>

app/views/jobs/show.html.erb
<div class="job-content">
<h1 class="jobtitle"><%= @job.title %></h1>
<p class="date">
 <%= t("job.posted") %>: <%= @job.created_at.to_date %>
 
 <% if @job.owned_by?(current_user)  %>
 	<%= t("job.deadline") %>: <%= @job.deadline || t("job.deadline_forever") %>
 	<span class="manage">
 	<%= link_to t(:edit), edit_job_path(@job), :class => "edit" %>	
 	<% if @job.closed? %>
 		<%= link_to t(:open), open_job_path(@job), :confirm => t(:are_you_sure), :method => :put, :class => "open" %>
 	<% else %>
 		<%= link_to t(:close), close_job_path(@job), :confirm => t(:are_you_sure), :method => :put, :class => "close" %>
 	<% end %>	
 	<%= link_to t(:delete), job_path(@job), :confirm => t(:are_you_sure), :method => :delete, :class => "delete" %>
 	</span>	
 <% elsif @job.deadline %>
 	<%= t("job.deadline") %>: <%= @job.deadline %>
 <% end %>
</p>

<div class="social">

    <div class="social">
      <div class="fb-like" data-href="<%= job_url(@job) %>" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false" data-font="segoe ui"></div>
      <g:plusone href="<%= job_url(@job) %>" size="Medium"></g:plusone>
    </div>

</div>

<%= render :partial => "job", :object => @job %>

<a href="/" class="backto">Back to job board</a>
</div>

app/views/jobs/show.mobile.erb
<div data-role="page">
  <header data-role="header">
    <h1><%= @job.title %></h1>
    <%= link_to 'Jobs', root_path, "data-icon" => "arrow-l", "class" => "ui-btn-left" %>
    <% if @job.owner == current_user %>
    <%= link_to 'Edit', edit_job_path(@job), "data-icon" => "edit", "class" => "ui-btn-right" %>
    <% end %>
  </header>

  <div data-role="content">
    <%= render :partial => "job", :object => @job %>
    <%= render "shared/foot" %>
  </div><!-- content -->

  <footer data-role="footer">
    <h4>Ruby.tw</h4>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= render_page_image_link_tag %>

  <meta property="og:title" content="<%= page_title || SeoHelper.configuration.site_name %>"/>
  <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
  <meta property="og:image:url" content="<%= page_image || SeoHelper.configuration.default_page_image %>"/>

  <link rel="shortcut icon" href="/favicon.ico">
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= auto_discovery_link_tag(:rss, "http://feeds.feedburner.com/rubyjobs-taiwan", :title => "Ruby Jobs in Taiwan RSS feed") %>

<script type="text/javascript">
	$(function(){
		$.fn.formLabels();
		$("#search-form").submit(function(){
			var formVal = $("form").serialize();
			parent.$("#default div.results").html(formVal);
		})
	});
</script>

<%= csrf_meta_tag %>
</head>
<body>
<div id="wrapper">
    <div id="header">
        <h1><a href="/">RubyJobs</a></h1>
        <div class="right">
            <p class="member">
              <%= render :partial => "common/usernav" %>
            </p>
            <%= render :partial => "common/search_form" %>
        </div>
    </div>
    <div id="container">
        <div id="container-inner">
          <%= flash_messages %>
          <%= yield %>
        </div>
    </div>
    <div id="footer">
        <ul class="menu clearfix">
            <li><%= link_to t(:faq), about_path %></li>
            <li><%= link_to t(:rss_feed), "http://feeds.feedburner.com/rubyjobs-taiwan" %></li>
            <li class="twitter"><%= link_to t(:twitter), "http://twitter.com/rubytaiwan" %></li>
        </ul>
        <p class="language">Choose your language:
			<%= link_to "English", :controller => controller.controller_name,
					         :action => controller.action_name, :locale => "en" %>
			<%= link_to "繁體中文", :controller => controller.controller_name,
					         :action => controller.action_name, :locale => "zh_tw" %>
	    </p>
        <address>The job board is a free service by <a href="http://ruby.tw">Ruby Taiwan</a> and hosted by <a href="http://azure.microsoft.com" target="_blank">Microsoft Azure</a>.</address>
    </div>
</div>

  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
  <%= javascript_include_tag "application" %>
  <%= render :partial => "common/facebook_js" %>
  <%= google_plusone_javascript_include_tag(:async => true) %>
  <%= yield :scripts %>

<%= render :partial => "common/google_analytics" %>

</body>
</html>

app/views/pages/about.html.erb
<% if I18n.locale == :zh_tw %>
  <%= render :partial => "about_zh_tw" %>
<% else  %>
  <%= render :partial => "about_default" %>
<% end %>

app/views/shared/_foot.mobile.erb
<div class="foot">
  <p><a href="/about">FAQ</a> | The job board is a free service by <a href="http://ruby.tw/">Ruby Taiwan</a> and hosted by <a href="http://azure.microsoft.com">Microsoft Azure</a></p>
<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, "class" => "ui-btn-right", :rel => "external" %>
<% else %>
  <fieldset class="ui-grid-a">
    <div class="ui-block-a"><%= link_to 'Sign In', new_session_path(:user),      "data-role" => "button" %></div>
    <div class="ui-block-b"><%= link_to 'Sign Up', new_registration_path(:user), "data-role" => "button" %></div>
  </fieldset>
<% end %>
</div>